import random,sys,time,json,datetime
from os import system
from colorama import Fore
from sys import platform
currentTime = time.ctime()
if platform == "win32": #Windows
  system("cls")
if platform == "linux" or platform == "linux2": #Linux
  system("clear")
if platform == "darwin": #Mac OS
  system("clear")
card = ["5434536074348861 ","5434532588675741","5434533623513731","5434535874280571","5434530512621773","5434531861000536","5434532425076772","5434530627170070",
"5434532063556515","5434531544777435","4394318993520586", "4590252038475005", "4342994192025594", "4342 994192025594""4519530206525034","4519537435247116","4519530148264262","4519538526411710","4519531178576583","4519531354313264","4519535512880775","4519535366263375","4519533735644417","4519537806147515",]
cvc = ["654","251","185","042","844","841","914","104","041","851","067","492","414","094","553","086","151","633","426","457","852","672""453"]
expires = ["02/2027","01/2028","11/2027","05/2028","11/2028","09/2026","07/2028","09/2026","03/2027","04/2028",
"08/28","04/27","01/28","05/26","02/2025","02/2028","01/2025","10/2025","01/2027","07/2025","04/2027","11/2028","02/2028"]
print(Fore.GREEN+""""
   ******  *******   ******** *******   ** **********   ******      **     *******   *******     ********  ******** ****     **
  **////**/**////** /**///// /**////** /**/////**///   **////**    ****   /**////** /**////**   **//////**/**///// /**/**   /**
 **    // /**   /** /**      /**    /**/**    /**     **    //    **//**  /**   /** /**    /** **      // /**      /**//**  /**
/**       /*******  /******* /**    /**/**    /**    /**         **  //** /*******  /**    /**/**         /******* /** //** /**
/**       /**///**  /**////  /**    /**/**    /**    /**        **********/**///**  /**    /**/**    *****/**////  /**  //**/**
//**    **/**  //** /**      /**    ** /**    /**    //**    **/**//////**/**  //** /**    ** //**  ////**/**      /**   //****
 //****** /**   //**/* *******/*******  /**    /**     //****** /**     /**/**   //**/*******   //******** /********/**    //***
  //////  //     // //////// ///////   //     //       //////  //      // //     // ///////     ////////  //////// //      ///  """)
time.sleep(1)
print(Fore.MAGENTA+"How many credit cards you want to gen? (max 10)")
time.sleep(1)
print(Fore.RED+"Type help, exit,or credits, restart,back for more information.")
gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "credits":
  print(Fore.BLUE+"""
    Made By Opw
    
    Discord = "opw#7777"

    Github = "github.com/Opwwww  
   
    Well wack did the time thing 
  """)
  gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "back":
  system('cmd /k "python main.py" ')
if gen == "restart":
   system('cmd /k "python gen.py"')
if gen == "help":
  print(Fore.RED+ """
     Just put a fucking number (1-10)
   """)
  gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "exit":
  sys.exit("Exitting..")
if gen == "1" or gen == "01":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "2" or gen == "02":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "3" or gen == "03":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "4" or gen == "04":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "5" or gen == "05":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "6" or gen == "06":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "7" or gen == "07":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "8" or gen == "08":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "9" or gen == "09":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
if gen == "10":
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    time.sleep(2)
    currentTime = time.ctime()
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Number: " + Fore.GREEN + (random.choice(card)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Cvc:  " + Fore.GREEN + (random.choice(cvc)))
    print(Fore.RED + "[" + currentTime.split(" ")[3]  + "]" + " Expires:  " + Fore.GREEN + (random.choice(expires)))
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")
else:
    print(Fore.RED+ "[-] Invalid option.")
    time.sleep(2)
    system("cls")
    gen = input(Fore.CYAN + "[" + currentTime.split(" ")[3]  + "]" + " >>> ")


 
    
